test_VAL_no_default: 1
synapse_server:
  server_name: "FUCK_YEA"
  server_url: null
  api_path: _synapse/admin/
  admin_api_path: _synapse/admin/
  bot_user_id: null
  bot_device_id: null
  bot_access_token: null
authentik_server:
  public_api_url: https://authentik.company.org/api/v3
  api_key: xxx
  sync_interval_seconds: 120
  account_pathes:
    - users
welcome_new_users_messages:
  - Welcome to the company chat. I am the company bot. I will invite you to the groups you are assigned. If you have any technical questions write a message to @admin-person:matrix.company.org.
sync_authentik_users_with_matrix_rooms:
  enabled: true
  authentik_username_mapping_attribute: username
  kick_matrix_room_members_not_in_mapped_authentik_group_anymore: true
  sync_only_users_in_authentik_pathes: null
  sync_only_users_with_authentik_attributes: null
  sync_only_users_of_groups_with_id: null
create_matrix_rooms_based_on_authentik_groups:
  enabled: true
  only_for_children_of_groups_with_uid: null
  only_groups_with_attributes:
    attribute.chatroom: true
  only_for_groupnames_starting_with: null
matrix_room_default_settings:
  alias_prefix: null
  matrix_alias_from_authentik_attribute: pk
  name_prefix: null
  matrix_name_from_authentik_attribute: name
  topic_prefix: null
  matrix_topic_from_authentik_attribute: attributes.chatroom_topic
  matrix_room_create_params_from_authentik_attribute: attribute.chatroom_params
  default_room_create_params:
    preset: private_chat
    visibility: private
per_authentik_group_pk_matrix_room_settings:
  80439f0d-d936-4118-8017-52a95d6dd1bc:
    alias_prefix: null
    matrix_alias_from_authentik_attribute: attribute.custom._FUCK_YEA
    name_prefix: null
    matrix_name_from_authentik_attribute: name
    topic_prefix: "TOPIC PREFIX FOR SPECIFIC ROOM:"
    matrix_topic_from_authentik_attribute: attributes.chatroom_topic
    matrix_room_create_params_from_authentik_attribute: attribute.chatroom_params
    default_room_create_params:
      preset: private_chat
      visibility: private
matrix_user_ignore_list:
  - "@admin:matrix.company.org"
authentik_user_ignore_list:
  - admin
authentik_group_ignore_list:
  - internal_company_group
deactivate_disabled_authentik_users_in_matrix:
  enabled: true
  erase: false
  gdpr_erase: true
