import os, sys

if __name__ == "__main__":
    SCRIPT_DIR = os.path.dirname(
        os.path.realpath(os.path.join(os.getcwd(), os.path.expanduser(__file__)))
    )
    MODULE_ROOT_DIR = os.path.join(SCRIPT_DIR, "..")
    sys.path.insert(0, os.path.normpath(MODULE_ROOT_DIR))
from onbot.main import run_bot


run_bot()
t = [
    {
        "room_id": "!ZdNfkeTOBfmuaelcuG:dzd-ev.org",
        "name": "Deutsches Zentrum für Diabetesforschung",
        "canonical_alias": "#DZD:dzd-ev.org",
        "joined_members": 1,
        "joined_local_members": 1,
        "version": "10",
        "creator": "@dzd-bot:dzd-ev.org",
        "encryption": None,
        "federatable": True,
        "public": False,
        "join_rules": "invite",
        "guest_access": "can_join",
        "history_visibility": "shared",
        "state_events": 9,
        "room_type": "m.space",
    },
    {
        "room_id": "!DbJRSjtmVTxctLHYVX:dzd-ev.org",
        "name": "TEST1",
        "canonical_alias": None,
        "joined_members": 2,
        "joined_local_members": 2,
        "version": "10",
        "creator": "@dzd-bot:dzd-ev.org",
        "encryption": None,
        "federatable": True,
        "public": False,
        "join_rules": "invite",
        "guest_access": "can_join",
        "history_visibility": "shared",
        "state_events": 9,
        "room_type": "m.space",
    },
    {
        "room_id": "!BBJUXilEogSjJWInSj:dzd-ev.org",
        "name": None,
        "canonical_alias": None,
        "joined_members": 0,
        "joined_local_members": 0,
        "version": "10",
        "creator": "@dzd-bot:dzd-ev.org",
        "encryption": None,
        "federatable": True,
        "public": False,
        "join_rules": None,
        "guest_access": None,
        "history_visibility": None,
        "state_events": 6,
        "room_type": "m.space",
    },
    {
        "room_id": "!EEBuOBJvKGnzfXbpeD:dzd-ev.org",
        "name": None,
        "canonical_alias": None,
        "joined_members": 0,
        "joined_local_members": 0,
        "version": "10",
        "creator": "@dzd-bot:dzd-ev.org",
        "encryption": None,
        "federatable": True,
        "public": False,
        "join_rules": None,
        "guest_access": None,
        "history_visibility": None,
        "state_events": 6,
        "room_type": "m.space",
    },
    {
        "room_id": "!FlydxyofcyfpTrdyKN:dzd-ev.org",
        "name": None,
        "canonical_alias": None,
        "joined_members": 0,
        "joined_local_members": 0,
        "version": "10",
        "creator": "@dzd-bot:dzd-ev.org",
        "encryption": None,
        "federatable": True,
        "public": False,
        "join_rules": None,
        "guest_access": None,
        "history_visibility": None,
        "state_events": 6,
        "room_type": "m.space",
    },
    {
        "room_id": "!GXhkXSmZECOITGHHMA:dzd-ev.org",
        "name": None,
        "canonical_alias": None,
        "joined_members": 0,
        "joined_local_members": 0,
        "version": "10",
        "creator": "@dzd-bot:dzd-ev.org",
        "encryption": None,
        "federatable": True,
        "public": False,
        "join_rules": None,
        "guest_access": None,
        "history_visibility": None,
        "state_events": 6,
        "room_type": "m.space",
    },
    {
        "room_id": "!TiITEqdtELrsPfKuAQ:dzd-ev.org",
        "name": None,
        "canonical_alias": None,
        "joined_members": 0,
        "joined_local_members": 0,
        "version": "10",
        "creator": "@dzd-bot:dzd-ev.org",
        "encryption": None,
        "federatable": True,
        "public": False,
        "join_rules": None,
        "guest_access": None,
        "history_visibility": None,
        "state_events": 6,
        "room_type": "m.space",
    },
    {
        "room_id": "!YLJCQCunXPlgwAkfln:dzd-ev.org",
        "name": None,
        "canonical_alias": None,
        "joined_members": 0,
        "joined_local_members": 0,
        "version": "10",
        "creator": "@dzd-bot:dzd-ev.org",
        "encryption": None,
        "federatable": True,
        "public": False,
        "join_rules": None,
        "guest_access": None,
        "history_visibility": None,
        "state_events": 6,
        "room_type": "m.space",
    },
    {
        "room_id": "!ZcpNKsQUAxhBjemNXe:dzd-ev.org",
        "name": None,
        "canonical_alias": None,
        "joined_members": 0,
        "joined_local_members": 0,
        "version": "10",
        "creator": "@dzd-bot:dzd-ev.org",
        "encryption": None,
        "federatable": True,
        "public": False,
        "join_rules": None,
        "guest_access": None,
        "history_visibility": None,
        "state_events": 8,
        "room_type": "m.space",
    },
    {
        "room_id": "!buSMyagnuZqGSUmdvZ:dzd-ev.org",
        "name": None,
        "canonical_alias": None,
        "joined_members": 0,
        "joined_local_members": 0,
        "version": "10",
        "creator": "@dzd-bot:dzd-ev.org",
        "encryption": None,
        "federatable": True,
        "public": False,
        "join_rules": None,
        "guest_access": None,
        "history_visibility": None,
        "state_events": 8,
        "room_type": "m.space",
    },
    {
        "room_id": "!ijcyJFioJDJJMPZkCA:dzd-ev.org",
        "name": None,
        "canonical_alias": None,
        "joined_members": 0,
        "joined_local_members": 0,
        "version": "10",
        "creator": "@dzd-bot:dzd-ev.org",
        "encryption": None,
        "federatable": True,
        "public": False,
        "join_rules": None,
        "guest_access": None,
        "history_visibility": None,
        "state_events": 7,
        "room_type": "m.space",
    },
    {
        "room_id": "!ygMnDlWfIePbKvuoyZ:dzd-ev.org",
        "name": None,
        "canonical_alias": None,
        "joined_members": 0,
        "joined_local_members": 0,
        "version": "10",
        "creator": "@dzd-bot:dzd-ev.org",
        "encryption": None,
        "federatable": True,
        "public": False,
        "join_rules": None,
        "guest_access": None,
        "history_visibility": None,
        "state_events": 6,
        "room_type": "m.space",
    },
]
